### PR TITLE
added initial SAC

### LINKED ISSUE #10: Implement Soft actor critic
@inproceedings{haarnoja2018soft,
  title={Soft actor-critic: Off-policy maximum entropy deep reinforcement learning with a stochastic actor},
  author={Haarnoja, Tuomas and Zhou, Aurick and Abbeel, Pieter and Levine, Sergey},
  booktitle={International conference on machine learning},
  pages={1861--1870},
  year={2018},
  organization={PMLR}
}

https://proceedings.mlr.press/v80/haarnoja18b/haarnoja18b.pdf

### PR DESCRIPTION
**Pull request by TheGogy**
Added initial Soft actor critic implemented.

Closes #10

### CODE REVIEW

**Comment by TheGogy** [comment]
https://github.com/user-attachments/assets/ee4f149e-a19f-4a8a-bfcd-4e5ba61a6414

It's more skipping than walking, as the two legs don't seem to cross, but it does seem to be converging well.

**Review by Tom-Pecher — COMMENTED** [review]
Should we maybe make the record.py file the same for all agents?

**Review by box1273002 — APPROVED** [review]

**Review by box1273002 — CHANGES_REQUESTED** [review]
I agree with tom

**Comment by TheGogy** [comment]
> Should we maybe make the record.py file the same for all agents?

This would work for all the agents done so far, as these are all actor-critic agents. Though it could be different, if we wanted to do, say, PPO.

**Comment by Tom-Pecher** [comment]
Well in that case we could do a match case with each family of models?

**Comment by TheGogy** [comment]
This would be possible, though it has been set up in the current way in order to be as flexible as possible between individual models.

**Comment by TheGogy** [comment]
Discrepancies in the recording script should be resolved in the abstract class feature: https://github.com/Tom-Pecher/RL-CW/tree/feature/abstract_agent_class

Closing and merging now.

**Pull request merged**
